name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14-alpine
        env:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: secret
          POSTGRES_DB: simple_bank
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
          
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ^1.23

    - name: Drop all tables in PostgreSQL Database
      run: |
        psql -U root -d simple_bank -c "DROP SCHEMA public CASCADE;"
        psql -U root -d simple_bank -c "CREATE SCHEMA public;"
      env:
        PGPASSWORD: secret

    - name: Install golang-migrate
      run: |
        curl -L https://github.com/golang-migrate/migrate/releases/download/v4.14.1/migrate.linux-amd64.tar.gz | tar xvz
        sudo mv migrate.linux-amd64 /usr/bin/migrate
        which migrate

    - name: Create database
      run: |
        PGPASSWORD=secret createdb -h localhost -U root bank

    - name: Run migrations
      run: make migrateup

    - name: Test
      run: make test